service: coffee-shop-api


provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    TABLE_NAME: ${self:service}-${self:provider.stage}-Menu
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}

functions:
  create:
    handler: handlers/create.handler
    events:
      - http:
          path: /
          method: post

  list:
    handler: handlers/list.handler
    events:
      - http:
          path: /
          method: get

  read:
    handler: handlers/read.handler
    events:
      - http:
          path: /{id}
          method: get

  update:
    handler: handlers/update.handler
    events:
      - http:
          path: /{id}
          method: put

  delete:
    handler: handlers/delete.handler
    events:
      - http:
          path: /{id}
          method: delete

  root:
    handler: handlers/root.handler
    events:
      - http:
          path: /welcome
          method: get

resources:
  Resources:
    MenuTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true

