name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  SERVICE: coffee-shop-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Deploy to DEV
        if: github.ref != 'refs/heads/prod'
        run: |
          npx serverless deploy --stage dev --verbose

      - name: Deploy to PROD
        if: github.ref == 'refs/heads/main'
        run: |
          npx serverless deploy --stage prod --verbose
