name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  SERVICE: coffee-shop-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Set up Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies (including local Serverless Framework)
      - name: Install dependencies
        run: npm ci

      # Run tests
      - name: Run tests
        run: npm test

      # Deploy to DEV
      - name: Deploy to DEV
        if: github.ref != 'refs/heads/prod'
        run: |
          npx serverless deploy --stage dev --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

      # Deploy to PROD
      - name: Deploy to PROD
        if: github.ref == 'refs/heads/main'
        run: |
          npx serverless deploy --stage prod --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
